apiVersion: v1
data:
  x-forward-for: "https"
  x-forward-for-proto: "https"
  proxy-preserve-host: "on"
  proxy-connect-timeout: "15"
  proxy-read-timeout: "600"
  proxy-send-imeout: "600"
  hsts-include-subdomains: "false"
  body-size: "64m"
  server-name-hash-bucket-size: "256"
kind: ConfigMap
metadata:
  namespace: nginx
  name: nginx
